Repository IBM/test-infra, pull requests merged in 2019-12, with the labels that each got.

#42 Add lint job in mcm foundation
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
Labels: approved, lgtm, ok-to-test, size/M

#43 add ssh token and clone uri for prow job.
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
Labels: approved, lgtm, size/XS

#44 create prow job for multicloud-operators-cluster-controller
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/OWNERS
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml
Labels: approved, lgtm, ok-to-test, size/L

#45 Add image build job
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
Labels: approved, lgtm, ok-to-test, size/S

#46 move image build job to travis.
  prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
  prow/config.yaml
Labels: approved, size/M

#47 update branche protection for go-repo-template.
  prow/config.yaml
Labels: approved, size/S

#48 update branch protection context name.
  prow/config.yaml
Labels: approved, size/XS

#49 remove prow job for go-repo-template.
  prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
  prow/cluster/jobs/IBM/go-repo-template/OWNERS
Labels: approved, lgtm, size/L

#50 move to old status check context for travis.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#51 move to old status check context for travis.
  prow/config.yaml
Labels: approved, size/XS

#52 add github.com/rh-ibm-synergy to GOPRIVATE
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#53 update multicloud-operators-cluster-controller prow job
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#54 update prow job fpr build tool images.
  docker/build-tools/Dockerfile
  docker/build-tools/build-and-push.sh
  docker/docker-in-docker/docker-tools/Dockerfile
  docker/docker-in-docker/docker-tools/Makefile
  docker/docker-in-docker/docker-tools/install.sh
  docker/docker-in-docker/docker-tools/prow-runner.sh
  prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.yaml
Labels: approved, size/XL

#55 sync build-tools docker.
  Makefile
  prow/cluster/jobs/IBM/multicloud-operators-channel/IBM.multicloud-operators-channel.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-deployable/IBM.multicloud-operators-deployable.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-subscription-release/IBM.multicloud-operators-subscription-release.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-subscription/IBM.multicloud-operators-subscription.master.yaml
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
  prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
  prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.master.yaml
  prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.yaml
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
  prow/docker/build-tools/Dockerfile
  prow/docker/build-tools/build-and-push.sh
  prow/docker/docker-in-docker/Dockerfile
  prow/docker/docker-in-docker/build-and-push.sh
  prow/docker/docker-in-docker/install.sh
  prow/docker/docker-in-docker/prow-runner.sh
Labels: approved, lgtm, size/XL

#56 add ssh secret volumn and mount to preset
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#57 remove duplicated secret volume.
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml
Labels: approved, lgtm, size/XS

#59 fix presets for private repos.
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml
  prow/config.yaml
Labels: approved, size/M
