Repository IBM/test-infra, pull requests merged in 2019-10, with the labels that each got.

#19 add tide auto merge plugin for multicloud repos.
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, lgtm, size/S

#20 add placementrule to jobs
  prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-placementrule/OWNERS
Labels: approved, lgtm, size/L

#21 update build tools image.
  prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
Labels: approved, lgtm, size/S

#22 update build tools image to add kubebuilder.
  prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
  prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
  prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.master.yaml
Labels: approved, lgtm, size/M

#23 fix incorrect kubebuilder path in build-tools image.
  prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
  prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
  prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.master.yaml
Labels: approved, lgtm, size/M

#24 update build-tools && add env.
  prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
  prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
  prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/M

#25 add all mcm app lifecycle repos
  prow/cluster/jobs/IBM/multicloud-operators-channel/IBM.multicloud-operators-channel.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-channel/OWNERS
  prow/cluster/jobs/IBM/multicloud-operators-deployable/IBM.multicloud-operators-deployable.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-deployable/OWNERS
  prow/cluster/jobs/IBM/multicloud-operators-subscription/IBM.multicloud-operators-subscription.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-subscription/OWNERS
Labels: approved, lgtm, size/L

#26 update rerun command.
  prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-channel/IBM.multicloud-operators-channel.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-deployable/IBM.multicloud-operators-deployable.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-subscription/IBM.multicloud-operators-subscription.master.yaml
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
  prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
  prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.master.yaml
Labels: approved, lgtm, size/M

#27 add env for kubebuilder.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#28 add codecov for oasis.
  prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
Labels: approved, lgtm, size/S

#29 add codecov got go-repo-template.
  prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
Labels: approved, lgtm, size/S

#30 addcodecov for mcm operators repos.
  prow/cluster/jobs/IBM/multicloud-operators-channel/IBM.multicloud-operators-channel.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-deployable/IBM.multicloud-operators-deployable.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-subscription/IBM.multicloud-operators-subscription.master.yaml
Labels: approved, lgtm, size/M

#31 move codecov to postsubmit.
  prow/cluster/jobs/IBM/go-repo-template/IBM.go-repo-template.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-channel/IBM.multicloud-operators-channel.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-deployable/IBM.multicloud-operators-deployable.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-subscription/IBM.multicloud-operators-subscription.master.yaml
  prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
Labels: approved, lgtm, size/L

#32 onboard new repo.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#33 add resource request for check job.
  prow/cluster/jobs/IBM/multicloud-operators-subscription/IBM.multicloud-operators-subscription.master.yaml
Labels: approved, size/XS

#34 add subscription-release repo
  prow/cluster/jobs/IBM/multicloud-operators-subscription-release/IBM.multicloud-operators-subscription-release.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-subscription-release/OWNERS
Labels: approved, lgtm, size/L

#35 onboard new repo.
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, size/S

#36 update repo name.
  prow/config.yaml
Labels: approved, size/XS

#37 add mcm foudnation prow job
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/IBM.multicloud-operators-foundation.master.yaml
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/OWNERS
Labels: approved, lgtm, ok-to-test, size/M

#38 tune prow job configurations.
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
Labels: approved, lgtm, size/M

#39 update path alias for prowjob.
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
Labels: approved, lgtm, size/S

#40 add ssh key secrets for private repos.
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
Labels: approved, size/M

#41 update prow job name.
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
Labels: approved, lgtm, size/XS
