Repository IBM/test-infra, pull requests merged in 2020-06, with the labels that each got.

#176 ibm-heathcheck-operator multiarch build for prow
  prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
Labels: approved, lgtm, size/L

#177 add multiarch build jobs for ibm-healthcheck-operator.
  prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
Labels: approved, lgtm, size/L

#178 update repo name for ibm-grafana-operator to ibm-monitoring-grafana-o…
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/M

#179 onboard hybridapp-io/ham-placement.
  prow/cluster/jobs/hybridapp-io/ham-placement/hybridapp-io.ham-placement.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#180 enable multiarch for licensing
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.feature_z_p_support.yaml
Labels: approved, lgtm, size/L

#181 fix image for multiarch_build_ibm-licensing-operator.
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.feature_z_p_support.yaml
Labels: approved, lgtm, size/M

#182 licensing - updated image for image build job
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.feature_z_p_support.yaml
Labels: approved, lgtm, size/XS

#183 fix image for multiarch_build_ibm-licensing-operator.
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.feature_z_p_support.yaml
Labels: approved, lgtm, size/XS
