Repository IBM/test-infra, pull requests merged in 2020-09, with the labels that each got.

#236 revert prowjob for ibm-monitoring-grafana-operator.
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
Labels: approved, lgtm, size/L

#237 remove unused periodic jobs.
  prow/cluster/jobs/all-periodics.yaml
Labels: approved, lgtm, size/XS

#238 update prow job for ibm-grafana-ocpthanos-proxy.
  prow/cluster/jobs/IBM/ibm-grafana-ocpthanos-proxy/IBM.ibm-grafana-ocpthanos-proxy.master.yaml
Labels: approved, lgtm, size/L

#239 Revert "update prow job for ibm-grafana-ocpthanos-proxy."
  prow/cluster/jobs/IBM/ibm-grafana-ocpthanos-proxy/IBM.ibm-grafana-ocpthanos-proxy.master.yaml
Labels: approved, lgtm, size/L

#240 onboard IBM/prometheus-metrics-server-simulator.
  prow/cluster/jobs/IBM/prometheus-metrics-server-simulator/ibm.prometheus-metrics-server-simulator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#241 cut release branch v3.1.5 for elastic-stack-operator.
  prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.release-v3.1.5.yaml
Labels: approved, lgtm, size/L

#242 Allow development jobs
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.development.yaml
Labels: approved, lgtm, size/L

#243 fix incorrect path alias.
  prow/cluster/jobs/IBM/ibm-licensing-hub-operator/IBM.ibm-licensing-hub-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.development.yaml
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
Labels: approved, lgtm, size/XS

#244 add new approver.
  OWNERS
Labels: approved, lgtm

#245 fix multiarch image build for ibm-elastic-stack-operator.
  prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.master.yaml
Labels: approved, lgtm, size/L

#246 sync prow deploy manifests.
  prow/cluster/deploy/cherry-picker.yaml
  prow/cluster/deploy/need-rebase.yaml
  prow/cluster/deploy/prow-all-in-one.yaml
Labels: approved, lgtm, size/M
