Repository IBM/test-infra, pull requests merged in 2020-11, with the labels that each got.

#257 fix incorrect secret name.
  prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
Labels: approved, lgtm, size/XS

#258 remove codecov test for ibm-ingress-nginx-operator.
  prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
Labels: approved, lgtm, size/S

#259 create release 4.0 branch for common-service-operator
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.release-4.0.yaml
Labels: approved, size/L

#260 updated helm to v3.4.1
  prow/docker/build-tool/Dockerfile
  prow/docker/check-tool/Dockerfile
Labels: approved, lgtm, size/XS

#261 fix broken helm download link.
  prow/docker/build-tool/Dockerfile
Labels: approved, lgtm, size/XS

#262 fix broken helm download link.
  prow/docker/check-tool/Dockerfile
Labels: approved, lgtm, size/XS

#263 update build-tool and check-tool images for go-repo-template.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.master.yaml
Labels: approved, lgtm, size/M

#264 updated build tool and check tool images for platform-api-operator
  prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
Labels: approved, lgtm, size/S

#265 fix incorrect check-tool image.
  prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
Labels: approved, lgtm, size/XS

#266 create release 4.0 branch for licensing operator
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.release-4.0.yaml
Labels: approved, lgtm, ok-to-test, size/L

#267 Revert image
  prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
Labels: approved, lgtm, size/S

#268 upgrade golang version for building images.
  prow/docker/build-tool/Dockerfile
  prow/docker/check-tool/Dockerfile
Labels: approved, lgtm, size/XS

#269 update building images.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.master.yaml
Labels: approved, lgtm, size/M
