Repository IBM/test-infra, pull requests merged in 2020-08, with the labels that each got.

#196 remove build job for odlm and cs-operator.
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
Labels: approved, lgtm, size/L

#197 upgrade build-tool.
  prow/docker/build-tool/Dockerfile
Labels: approved, lgtm, size/S

#198 upgrade build-tool.
  prow/docker/build-tool/Dockerfile
Labels: approved, lgtm, size/XS

#199 update build-tool image for odlm.
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
Labels: approved, lgtm, size/S

#201 upgrade check-tool.
  prow/docker/check-tool/Dockerfile
Labels: approved, lgtm, size/XS

#202 upgrade check-tool.
  prow/docker/check-tool/Dockerfile
Labels: approved, lgtm, size/XS

#203 upgrade base images for go-repo-template.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.master.yaml
Labels: approved, lgtm, size/M

#204 fix build-tool.
  prow/docker/build-tool/Dockerfile
Labels: approved, lgtm, size/XS

#205 upgrade base images for go-repo-template.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.master.yaml
Labels: approved, lgtm, size/S

#206 fix build-tool.
  prow/docker/build-tool/Dockerfile
  prow/docker/check-tool/Dockerfile
Labels: approved, lgtm, size/XS

#207 upgrade base images.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.master.yaml
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
Labels: approved, lgtm, size/M

#200 update build tool version for License Service
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
Labels: approved, lgtm, size/M

#208 update build && check tool version for installer repos
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.master.yaml
  prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
Labels: approved, lgtm, size/M

#209 add prow job for ibm-grafana-ocpthanos-proxy.
  prow/cluster/jobs/IBM/ibm-grafana-ocpthanos-proxy/IBM.ibm-grafana-ocpthanos-proxy.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#210 update build tool version for Healthcheck Operator
  prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
Labels: approved, lgtm, size/M

#211 update build-tool image.
  prow/cluster/jobs/IBM/deployer-operator/ibm.deployer-operator.master.yaml
  prow/cluster/jobs/IBM/hybridapplication-operator/ibm.hybridapplication-operator.master.yaml
  prow/cluster/jobs/IBM/hybriddeployable-operator/ibm.hybriddeployable-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-licensing-hub-operator/IBM.ibm-licensing-hub-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
  prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.master.yaml
  prow/cluster/jobs/hybridapp-io/ham-deploy/hybridapp-io.ham-deploy.master.yaml
  prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.master.yaml
  prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.release.yaml
  prow/cluster/jobs/hybridapp-io/ham-placement/hybridapp-io.ham-placement.master.yaml
  prow/cluster/jobs/hybridapp-io/ham-resource-discoverer/hybridapp-io.ham-resource-discoverer.master.yaml
Labels: approved, lgtm, size/L

#212 add doc and tool to build pod-utility.
  prow/docker/pod-utility/Dockerfile.podutilitybinaries
  prow/docker/pod-utility/Dockfile.clonerefs
  prow/docker/pod-utility/Dockfile.entrypoint
  prow/docker/pod-utility/Dockfile.initupload
  prow/docker/pod-utility/Dockfile.sidecar
  prow/docker/pod-utility/README.md
  prow/docker/pod-utility/create_utility_images.sh
  prow/docker/pod-utility/patch_bazel.diff
  prow/docker/pod-utility/patch_nodejs.diff
Labels: approved, lgtm, size/L

#214 move to newer build container for tool upgrades
  prow/cluster/jobs/IBM/ibm-metering-multicloudui-operator/IBM.ibm-metering-multicloudui-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-receiver-operator/IBM.ibm-metering-receiver-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-sender-operator/IBM.ibm-metering-sender-operator.master.yaml
Labels: approved, lgtm, size/M

#213 update build tool version for ibm-auditlogging-operator
  prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
Labels: approved, lgtm, size/S

#215 use check-tool for check job.
  prow/cluster/jobs/IBM/ibm-metering-multicloudui-operator/IBM.ibm-metering-multicloudui-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-receiver-operator/IBM.ibm-metering-receiver-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-sender-operator/IBM.ibm-metering-sender-operator.master.yaml
Labels: approved, lgtm, size/S

#216 Remove build job for the amd64
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
Labels: approved, lgtm, size/M

#219 fix build tool for ibm-auditlogging-operator
  prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
Labels: approved, lgtm, size/S

#218 Update build tool version for ibm-cert-manager-operator
  prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
Labels: approved, lgtm, size/S

#217 update post submit container
  prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
Labels: approved, lgtm, size/XS

#220 upgrade golang for build-tool and check-tool.
  prow/docker/build-tool/Dockerfile
  prow/docker/check-tool/Dockerfile
Labels: approved, lgtm

#221 update build-tool image for build-tool.
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
Labels: approved, lgtm

#222 use wget to download binaries.
  prow/docker/build-tool/Dockerfile
Labels: approved, lgtm

#223 fix check image for prow jobs.
  prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
Labels: approved, lgtm, size/XS

#224 fix mtu issue on ppc64le build-tool.
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
  prow/docker/build-tool/docker-entrypoint.sh
Labels: approved, lgtm, size/XS

#225 support local build.
  Makefile
Labels: approved, lgtm, size/S

#226 fix mtu issue on ppc64le build-tool.
  prow/docker/build-tool/docker-entrypoint.sh
Labels: approved, lgtm, size/XS

#227 fix mtu issue on ppc64le build-tool.
  prow/docker/build-tool/docker-entrypoint.sh
Labels: approved, lgtm, size/S

#228 fix mtu issue on ppc64le build-tool.
  prow/docker/build-tool/docker-entrypoint.sh
Labels: approved, lgtm, size/XS

#229 upgrade build-tool image for prowjobs.
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
Labels: approved, lgtm, size/S

#230 upgrade build-tool and check-tool.
  prow/docker/build-tool/Dockerfile
  prow/docker/check-tool/build-and-push.sh
Labels: approved, lgtm, size/XS

#231 upgrade build-tool and check-tool.
  prow/cluster/jobs/IBM/deployer-operator/ibm.deployer-operator.master.yaml
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.master.yaml
  prow/cluster/jobs/IBM/hybridapplication-operator/ibm.hybridapplication-operator.master.yaml
  prow/cluster/jobs/IBM/hybriddeployable-operator/ibm.hybriddeployable-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.master.yaml
  prow/cluster/jobs/IBM/ibm-grafana-ocpthanos-proxy/IBM.ibm-grafana-ocpthanos-proxy.master.yaml
  prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-licensing-hub-operator/IBM.ibm-licensing-hub-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-multicloudui-operator/IBM.ibm-metering-multicloudui-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-receiver-operator/IBM.ibm-metering-receiver-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-sender-operator/IBM.ibm-metering-sender-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
  prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.master.yaml
  prow/cluster/jobs/hybridapp-io/ham-deploy/hybridapp-io.ham-deploy.master.yaml
  prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.master.yaml
  prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.release.yaml
  prow/cluster/jobs/hybridapp-io/ham-placement/hybridapp-io.ham-placement.master.yaml
  prow/cluster/jobs/hybridapp-io/ham-resource-discoverer/hybridapp-io.ham-resource-discoverer.master.yaml
Labels: approved, lgtm, size/XL

#232 Remove testing on power and z for ODLM
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
Labels: approved, lgtm, size/M

#233 remove build jobs for secretshare
  prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
Labels: approved, lgtm, size/M

#234 update old build-tools image.
  prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-catalog-ui-operator/IBM.ibm-catalog-ui-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-helm-api-operator/IBM.ibm-helm-api-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-helm-repo-operator/IBM.ibm-helm-repo-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-licensing-hub-operator/IBM.ibm-licensing-hub-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-management-repo-operator/IBM.ibm-management-repo-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-multicloudui-operator/IBM.ibm-metering-multicloudui-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-receiver-operator/IBM.ibm-metering-receiver-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-sender-operator/IBM.ibm-metering-sender-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-mongodb-operator/IBM.ibm-mongodb-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-exporters-operator/IBM.ibm-monitoring-exporters-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-prometheus-operator-ext:/IBM.ibm-monitoring-prometheus-operator-ext.master.yaml
  prow/cluster/jobs/IBM/ibm-mt-grqenforcer-operator/IBM.ibm-mt-grqenforcer-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-channel/IBM.multicloud-operators-channel.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-deployable/IBM.multicloud-operators-deployable.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-placementrule/IBM.multicloud-operators-placementrule.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-subscription-release/IBM.multicloud-operators-subscription-release.master.yaml
  prow/cluster/jobs/IBM/multicloud-operators-subscription/IBM.multicloud-operators-subscription.master.yaml
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
  prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
  prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.master.yaml
  prow/cluster/jobs/multicloudlab/tools/multicloudlab.tools.yaml
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-cluster-controller/rh-ibm-synergy.multicloud-operators-cluster-controller.master.yaml
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
Labels: approved, lgtm, size/L

#235 using build-tool as the code coverage job image
  common/Makefile.common.mk
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
Labels: approved, lgtm, size/XS
