Repository IBM/test-infra, pull requests merged in 2020-10, with the labels that each got.

#247 update build-tool image for prowjobs.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template-release-1.1.yaml
Labels: approved, lgtm

#248 fix prow jobs for ibm-ingress-nginx-operator.
  prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
Labels: approved, lgtm, size/L

#249 update prow jobs for ibm-ingress-nginx-operator.
  prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
Labels: approved, lgtm, size/S

#250 update prow jobs for ibm-ingress-nginx-operator.
  prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
Labels: approved, lgtm, size/XS

#252 cut release-3.7 branch for the ibm-metering-operator
  prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.release-3.7.yaml
Labels: approved, lgtm, size/L

#253 add new reviewers and approvers.
  OWNERS
Labels: approved, lgtm, size/S

#254 audit - use build tool for coverage
  prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
Labels: approved, lgtm, size/XS

#255 Onboard new operator ibm-namespace-scope-operator
  prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L
