Repository IBM/test-infra, pull requests merged in 2020-07, with the labels that each got.

#186 onboard three new metering repos.
  prow/cluster/jobs/IBM/ibm-metering-multicloudui-operator/IBM.ibm-metering-multicloudui-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-receiver-operator/IBM.ibm-metering-receiver-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-sender-operator/IBM.ibm-metering-sender-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#187 onboard ibm-licensing-hub-operator.
  prow/cluster/jobs/IBM/ibm-licensing-hub-operator/IBM.ibm-licensing-hub-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#188 cut test branch release-1.2 for ibm-commonui-operator.
  prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.release-1.2.yaml
Labels: approved, lgtm, size/L

#189 onboard ibm-secretshare-operator
  prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#190 cut release-3.6 branch for ibm-helm-api-operator repo.
  prow/cluster/jobs/IBM/ibm-helm-api-operator/IBM.ibm-helm-api-operator.release-3.6.yaml
Labels: approved, lgtm, size/L

#191 cut release branch for ibm-platform-api-operator.
  prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.release-3.6.yaml
Labels: approved, lgtm, size/L

#192 cut release-0.0.1 release branch for ham-application-assembler.
  prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.release-0.0.1.yaml
Labels: approved, lgtm, size/L

#193 cut release branch for ham-deployable-operator
  prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.release.yaml
Labels: approved, lgtm, size/L

#194 fix branch regex for prow jobs.
  prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.release.yaml
Labels: approved, lgtm

#195 release-.* for hybridapp projects
  prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.release.yaml
  prow/cluster/jobs/hybridapp-io/ham-deploy/hybridapp-io.ham-deploy.release.yaml
  prow/cluster/jobs/hybridapp-io/ham-placement/hybridapp-io.ham-placement.release.yaml
  prow/cluster/jobs/hybridapp-io/ham-resource-discoverer/hybridapp-io.ham-resource-discoverer.release.yaml
Labels: approved, lgtm, size/XL
