Repository IBM/test-infra, pull requests merged in 2020-02, with the labels that each got.

#85 onboard ibm-mt-grqenforcer-operator.
  prow/cluster/jobs/IBM/ibm-mt-grqenforcer-operator/IBM.ibm-mt-grqenforcer-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#86 replace rh-ibm-synergy/multicloud-operators-foundation import path
  prow/cluster/jobs/rh-ibm-synergy/multicloud-operators-foundation/rh-ibm-synergy.multicloud-operators-foundation.master.yaml
Labels: approved, lgtm, ok-to-test, size/S

#87 update the repo name from common-service-operator to meta-operator.
  prow/cluster/jobs/IBM/meta-operator/IBM.meta-operator.master.yaml
  prow/cluster/jobs/IBM/meta-operator/OWNERS
  prow/config.yaml
Labels: approved, lgtm, size/M

#88 Add the cert-manager-operator to be integrated into prow.
  prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-cert-manager-operator/OWNERS
Labels: approved, lgtm, size/L

#89 support multiarch build.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#90 using utility images from quay.io
  prow/config.yaml
Labels: approved, lgtm, size/XS

#91 use prow to build go-repo-template.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#92 onboard IBM/ibm-cert-manager-operator.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#93 onboard IBM/ibm-iam-operator.
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#94 onboard healthcheck-service-operator.
  prow/cluster/jobs/IBM/healthcheck-service-operator/IBM.healthcheck-service-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#95 onboard ibm-auditlogging-operator.
  prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#96 onboard ibm-commonui-operator.
  prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#99 onboard ibm-helm-api-operator
  prow/cluster/jobs/IBM/ibm-helm-api-operator/IBM.ibm-helm-api-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-helm-api-operator/OWNERS
Labels: approved, lgtm, size/L

#97 onboard ibm-management-repo-operator
  prow/cluster/jobs/IBM/ibm-management-repo-operator/IBM.ibm-management-repo-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-management-repo-operator/OWNERS
Labels: approved, lgtm, size/L

#98 onboard ibm-helm-repo-operator
  prow/cluster/jobs/IBM/ibm-helm-repo-operator/IBM.ibm-helm-repo-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-helm-repo-operator/OWNERS
Labels: approved, lgtm, size/L

#100 onaboard ibm-mongodb-operator.
  prow/cluster/jobs/IBM/ibm-mongodb-operator/IBM.ibm-mongodb-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#101 config tide for new repos.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#103 Update the prow jobs for ibm helm rep operators
  prow/cluster/jobs/IBM/ibm-helm-api-operator/IBM.ibm-helm-api-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-helm-repo-operator/IBM.ibm-helm-repo-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-management-repo-operator/IBM.ibm-management-repo-operator.master.yaml
Labels: approved, lgtm, size/L

#104 onaboard management ingress and nginx ingress repo.
  prow/cluster/jobs/IBM/ingress-nginx-operator/IBM.ingress-nginx-operator.master.yaml
  prow/cluster/jobs/IBM/management-ingress-operator/IBM.management-ingress-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#105 update repo name for ibm-healthcheck-operator.
  prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/M

#106 add more plugins to manage github issues.
  prow/plugins.yaml
Labels: approved, lgtm, size/S

#107 update name for two ingress repos.
  prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/M

#108 fix tide cinfigurations for two ingress repos.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#109 added myself to OWNERS for catalog and cloudctl operators
  prow/cluster/jobs/IBM/ibm-catalog-operator/OWNERS
  prow/cluster/jobs/IBM/ibm-cloudctl-operator/OWNERS
Labels: approved, lgtm, size/XS

#110 onboard monitoring operator repos
  prow/cluster/jobs/IBM/ibm-monitoring-exporters-operator/IBM.ibm-monitoring-exporters-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-prometheus-operator-ext:/IBM.ibm-monitoring-prometheus-operator-ext.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#111 update meta-operator repo name.
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/OWNERS
  prow/config.yaml
Labels: approved, lgtm, size/M

#112 add docker-in-docker s390 support.
  prow/docker/docker-in-docker/Dockerfile.s390x
  prow/docker/docker-in-docker/install.sh
Labels: approved, lgtm, size/M

#113 support build on s390x cluster.
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
  prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
Labels: approved, lgtm, size/M

#114 onnoard IBM/ibm-platform-api-operator.
  prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#115 update utility_images.
  prow/config.yaml
Labels: approved, lgtm, size/XS
