Repository IBM/test-infra, pull requests merged in 2020-03, with the labels that each got.

#116 enable more plugins for multicloudlab org.
  prow/plugins.yaml
Labels: approved, lgtm, size/XS

#117 onboard ibm-elastic-stack-operator.
  prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#118 update prowjobs for ibm-elastic-stack-operator.
  prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.master.yaml
Labels: approved, lgtm, size/S

#119 update utility_images.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#120 add dockerfiles.
  prow/dockerfiles/Dockfile.clonerefs
  prow/dockerfiles/Dockfile.entrypoint
  prow/dockerfiles/Dockfile.initupload
  prow/dockerfiles/Dockfile.sidecar
Labels: approved, lgtm, size/M

#121 add dockerfiles for more platform.
  prow/dockerfiles/Dockfile.clonerefs.ppc64le
  prow/dockerfiles/Dockfile.clonerefs.s390x
  prow/dockerfiles/Dockfile.entrypoint.ppc64le
  prow/dockerfiles/Dockfile.entrypoint.s390x
  prow/dockerfiles/Dockfile.initupload.ppc64le
  prow/dockerfiles/Dockfile.initupload.s390x
  prow/dockerfiles/Dockfile.sidecar.ppc64le
  prow/dockerfiles/Dockfile.sidecar.s390x
Labels: approved, lgtm, size/M

#122 add docker for build stage.
  prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
Labels: approved, lgtm, size/S

#123 support real multi-arch build for go-repo-template.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Labels: approved, lgtm, size/L

#124 update multi-arch build for go-repo-template.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Labels: approved, lgtm, size/L

#125 remove unused secrets.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Labels: approved, lgtm, size/S

#62 ppc64le support for build-tool
  prow/docker/build-tools/Dockerfile
Labels: size/M

#126 update prow job for build tools.
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
Labels: approved, lgtm, size/L

#127 refactor build tools.
  Makefile
  common/scripts/multiarch_image.sh
  prow/docker/build-tool/Dockerfile.amd64
  prow/docker/build-tool/Dockerfile.ppc64le
  prow/docker/build-tool/Dockerfile.s390x
  prow/docker/build-tool/build-and-push.sh
  prow/docker/build-tool/install.sh
  prow/docker/build-tool/prow-runner.sh
  prow/docker/build-tools/Dockerfile
  prow/docker/check-tool/Dockerfile
  prow/docker/check-tool/build-and-push.sh
Labels: approved, size/XL

#128 fix build tools.
  Makefile
  common/scripts/multiarch_image.sh
  prow/docker/build-tool/Dockerfile.amd64
  prow/docker/build-tool/Dockerfile.ppc64le
  prow/docker/build-tool/Dockerfile.s390x
  prow/docker/build-tool/install.sh
  prow/docker/check-tool/Dockerfile
Labels: approved, size/S

#129 fix build tools.
  prow/docker/build-tool/install.sh
  prow/docker/check-tool/Dockerfile
Labels: approved

#130 update check and build tool images.
  prow/docker/build-tool/Dockerfile.amd64
  prow/docker/build-tool/Dockerfile.ppc64le
  prow/docker/build-tool/Dockerfile.s390x
  prow/docker/build-tool/docker-entrypoint.sh
  prow/docker/build-tool/install.sh
  prow/docker/build-tool/prow-runner.sh
  prow/docker/check-tool/Dockerfile
Labels: approved, lgtm, size/XL

#131 fix check tool build.
  prow/docker/check-tool/Dockerfile
Labels: approved, lgtm, size/S

#132 update prow job for build-tool multiarch image.
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
Labels: approved, lgtm, size/XS

#133 fix build-tool image build.
  prow/docker/build-tool/Dockerfile.amd64
  prow/docker/build-tool/Dockerfile.ppc64le
  prow/docker/build-tool/Dockerfile.s390x
Labels: approved, lgtm, size/S

#134 fix build-tools image tag.
  Makefile
Labels: approved, lgtm, size/XS

#135 fix build-tools image build on ppc64le.
  prow/docker/build-tool/Dockerfile.ppc64le
  prow/docker/build-tool/build-and-push.sh
  prow/docker/check-tool/build-and-push.sh
Labels: approved, lgtm, size/XS

#136 revert built-tool ppc64le image.
  prow/docker/build-tool/Dockerfile.ppc64le
Labels: approved, lgtm, size/XS

#137 unify dockerfile for build-tool image.
  prow/docker/build-tool/Dockerfile
  prow/docker/build-tool/Dockerfile.amd64
  prow/docker/build-tool/Dockerfile.ppc64le
  prow/docker/build-tool/build-and-push.sh
Labels: approved, lgtm, size/L

#138 update build-tool images for prow jobs.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Labels: approved, lgtm, size/M

#139 add more tools to build tools images.
  prow/docker/build-tool/Dockerfile
  prow/docker/check-tool/Dockerfile
Labels: approved, lgtm, size/XS

#140 update build-tool image version for prow jobs.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Labels: approved, lgtm, size/M

#141 fix docker in docker settings.
  prow/docker/build-tool/Dockerfile
Labels: approved, lgtm

#142 update build-tool image version for prow jobs.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Labels: approved, lgtm, size/S

#143 update prow jobs for helm repos.
  prow/cluster/jobs/IBM/ibm-catalog-operator/IBM.ibm-catalog-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-catalog-ui-operator/IBM.ibm-catalog-ui-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-catalog-ui-operator/OWNERS
  prow/cluster/jobs/IBM/ibm-helm-repo-operator/IBM.ibm-helm-repo-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#144 fix docker-in-docker storage issue.
  prow/docker/build-tool/Dockerfile
Labels: approved, lgtm, size/XS

#145 update build-tool image version.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Labels: approved, lgtm, size/S

#146 support real multi-arch build for operand-deployment-lifecycle-manager.
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/OWNERS
Labels: approved, lgtm, size/L

#147 update details link for prow job.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#148 onaborad hybrid repos.
  prow/cluster/jobs/IBM/deployer-operator/ibm.deployer-operator.master.yaml
  prow/cluster/jobs/IBM/hybridapplication-operator/ibm.hybridapplication-operator.master.yaml
  prow/cluster/jobs/IBM/hybriddeployable-operator/ibm.hybriddeployable-operator.master.yaml
Labels: approved, lgtm, size/XL

#149 remove power and Z tests.
  prow/cluster/jobs/IBM/deployer-operator/ibm.deployer-operator.master.yaml
  prow/cluster/jobs/IBM/hybridapplication-operator/ibm.hybridapplication-operator.master.yaml
  prow/cluster/jobs/IBM/hybriddeployable-operator/ibm.hybriddeployable-operator.master.yaml
Labels: approved, lgtm, size/L

#150 config tide for hybrid repos.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#152 onboard repo ibm-grafana-operator.
  prow/cluster/jobs/IBM/ibm-grafana-operator/IBM.ibm-grafana-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L
