Repository IBM/test-infra, pull requests merged in 2020-12, with the labels that each got.

#270 Correct CS4.0 release branch name for License Service
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.release-4.0.yaml
Labels: approved, lgtm, ok-to-test, size/M

#271 create jobs for cs-3.6 odlm-1.4
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.release-3.6.yaml
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.release-1.4.yaml
Labels: approved, lgtm, size/L

#272 create IBM.ibm-iam-operator.release-3.8.yaml to enable build for 3.8 branch
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.release-3.8.yaml
Labels: approved, lgtm, size/L

#273 management-ingress release-1.4
  prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.release-1.4.yaml
Labels: approved, size/L

#274 create job for mongodb release-1.2
  prow/cluster/jobs/IBM/ibm-mongodb-operator/IBM.ibm-mongodb-operator.release-1.2.yaml
Labels: approved, size/L

#275 Change build for CS 3.6
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.release-3.6.yaml
Labels: approved, lgtm, needs-ok-to-test, size/M

#276 add ibm-iam-policy-operator
  prow/cluster/jobs/IBM/ibm-iam-policy-operator/IBM.ibm-iam-policy-operator.master.yaml
Labels: approved, lgtm, size/L

#277 fix: change master branch to main
  prow/cluster/jobs/IBM/ibm-iam-policy-operator/IBM.ibm-iam-policy-operator.main.yaml
Labels: approved, lgtm, size/S

#278 onboard ibm-iam-policy-operator
  prow/config.yaml
Labels: approved, size/XS

#279 upgrade go version for build check tool images.
  prow/docker/build-tool/Dockerfile
  prow/docker/check-tool/Dockerfile
Labels: approved, size/XS
