Repository IBM/test-infra, pull requests merged in 2020-04, with the labels that each got.

#153 No coverage job for platform-api-operator
  prow/cluster/jobs/IBM/ibm-cloudctl-operator/IBM.ibm-cloudctl-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-cloudctl-operator/OWNERS
  prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#154 fix postsubmit build for ibm-helm-repo-operator.
  prow/cluster/jobs/IBM/ibm-helm-repo-operator/IBM.ibm-helm-repo-operator.master.yaml
Labels: approved, lgtm, size/XS

#155 Postsubmit builds
  prow/cluster/jobs/IBM/ibm-catalog-ui-operator/IBM.ibm-catalog-ui-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-helm-api-operator/IBM.ibm-helm-api-operator.master.yaml
Labels: approved, lgtm, size/S

#156 add codecov prosubmit check.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Labels: approved, lgtm, size/S

#157 Revert "add codecov prosubmit check."
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.yaml
Labels: approved, lgtm

#158 add codecov prosubmit check.
  prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
Labels: approved, lgtm, size/S

#159 add multiarch_build for ibm-management-ingress-operator.
  prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
Labels: approved, lgtm, size/L

#160 onboard ibm-common-service-operator.
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operatormaster.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#161 watch release branch of ODLM
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.release-1.1.yaml
Labels: approved, lgtm, size/L

#162 add prow build for metering 35 maintenance
  prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.release-3.5.yaml
Labels: approved, lgtm, size/L

#163 add prow jobs for release-1.1 of go-repo-template.
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template-release-1.1.yaml
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template.master.yaml
Labels: approved, lgtm, size/L

#164 add prow build for auditlogging 35 maintenance
  prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.release-3.5.yaml
Labels: approved, lgtm, size/L

#165 onboard new repos for hybridapp-io org.
  prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.master.yaml
  prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.master.yaml
  prow/cluster/jobs/hybridapp-io/ham-resource-discoverer/hybridapp-io.ham-resource-discoverer.master.yaml
  prow/config.yaml
  prow/plugins.yaml
Labels: approved, lgtm, size/XL

#166 remove power and z tests for hybridapp-io.
  prow/cluster/jobs/hybridapp-io/ham-application-assembler/hybridapp-io.ham-application-assembler.master.yaml
  prow/cluster/jobs/hybridapp-io/ham-deployable-operator/hybridapp-io.ham-deployable-operator.master.yaml
  prow/cluster/jobs/hybridapp-io/ham-resource-discoverer/hybridapp-io.ham-resource-discoverer.master.yaml
Labels: approved, lgtm, size/L

#167 Add ibm-common-service-webhook
  prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhookmaster.yaml
Labels: approved, lgtm, size/L

#168 add tide config for ibm-common-service-webhook.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#169 add tide configuration for hybridapp-io repos.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#171 add prow jobs for ibm-iam-operator release-3.5.0
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.release-3.5.0.yaml
Labels: approved, lgtm, size/L
