Repository IBM/test-infra, pull requests merged in 2020-01, with the labels that each got.

#60 update tide url.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#61 onborad ibm-metering-operator.
  prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#63 Update owners for metering prow definition
  prow/cluster/jobs/IBM/ibm-metering-operator/OWNERS
Labels: approved, lgtm, size/XS

#64 set_catalog_owners
  prow/cluster/jobs/IBM/ibm-catalog-operator/OWNERS
Labels: approved, lgtm, size/XS

#65 onboard ibm-catalog-operator.
  prow/cluster/jobs/IBM/ibm-catalog-operator/IBM.ibm-catalog-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#67 update build env fro ibm-catalog-operator.
  prow/cluster/jobs/IBM/ibm-catalog-operator/IBM.ibm-catalog-operator.master.yaml
Labels: approved, size/XS

#66 Remove unwanted jobs for Catalog Operator
  prow/cluster/jobs/IBM/ibm-catalog-operator/IBM.ibm-catalog-operator.master.yaml
Labels: approved, lgtm, size/M

#68 fix docker start issue for ibm-catalog-operator build.
  prow/cluster/jobs/IBM/ibm-catalog-operator/IBM.ibm-catalog-operator.master.yaml
Labels: approved, lgtm, size/XS

#69 Adding ppc64le build support for docker-in-docker
  prow/docker/docker-in-docker/install.sh
Labels: approved, lgtm, size/XS

#70 onboard common-service-operator.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#71 fix secret name of code coverage job
  prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
Labels: approved, lgtm, size/XS

#72 Onboarding CloudCTL operator
  prow/cluster/jobs/IBM/ibm-cloudctl-operator/IBM.ibm-cloudctl-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-cloudctl-operator/OWNERS
Labels: approved, lgtm, size/M

#73 onboard ibm-cloudctl-operator.
  prow/config.yaml
Labels: approved, lgtm, size/XS

#74 support power for docker-in-docker tools.
  prow/docker/docker-in-docker/Dockerfile.amd64
  prow/docker/docker-in-docker/Dockerfile.ppc64le
  prow/docker/docker-in-docker/build-and-push.sh
Labels: approved, lgtm, size/M

#75 onboarding common service operator
  prow/cluster/jobs/IBM/common-service-operator/IBM.common-service-operator.master.yaml
  prow/cluster/jobs/IBM/common-service-operator/OWNERS
Labels: approved, lgtm, size/L

#76 keep revision for manifests in prow cluster
  prow/cluster/deploy/cherry-picker.yaml
  prow/cluster/deploy/need-rebase.yaml
  prow/cluster/deploy/starter.yaml
Labels: approved, lgtm, size/XXL

#77 added licensing prow job
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-licensing-operator/OWNERS
Labels: approved, lgtm, size/L

#79 add default cluster for prowjob of test-infra.
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
Labels: approved, size/M

#81 fix regex issue for prowjob configurations.
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
Labels: approved, size/XS

#78 support multiple build clusters.
  prow/cluster/deploy/starter.yaml
Labels: approved, size/S

#80 support multiple build clusters for oasis.
  prow/cluster/jobs/multicloudlab/oasis/multicloudlab.oasis.master.yaml
Labels: approved, size/L

#82 update postsubmit prowjob for docker builder.
  Makefile
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.yaml
Labels: approved, size/M

#83 fix incorrect secret name for coverage token.
  prow/cluster/jobs/IBM/common-service-operator/IBM.common-service-operator.master.yaml
Labels: approved, lgtm, size/XS

#84 onboard IBM/ibm-licensing-operator.
  prow/config.yaml
Labels: approved, size/XS
