Repository IBM/test-infra, pull requests merged in 2020-05, with the labels that each got.

#172 add tide configuration
  prow/config.yaml
Labels: approved, lgtm, size/XS

#173 Add prow job for ibm common service operator branch release-3.3
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.release-1.1.yaml
  prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.master.yaml
Labels: approved, lgtm, size/L

#174 onaboard hybridapp-io/ham-deploy.
  prow/cluster/jobs/hybridapp-io/ham-deploy/hybridapp-io.ham-deploy.master.yaml
  prow/config.yaml
Labels: approved, lgtm

#175 cut branch 3.4 for ibm-common-service-operator.
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.release-3.3.yaml
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.release-3.4.yaml
Labels: approved, lgtm, size/L
