Repository IBM/test-infra, pull requests merged in 2021-03, with the labels that each got.

#299 enable release-3.8 for auditlogging
  prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.release-3.8.yaml
Labels: approved, size/L

#302 Create IBM.ibm-commonui-operator.release-1.5.yaml
  prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.release-1.5.yaml
Labels: approved, lgtm, size/L

#303 Create IBM.ibm-mongodb-operator.release-1.3.yaml
  prow/cluster/jobs/IBM/ibm-mongodb-operator/IBM.ibm-mongodb-operator.release-1.3.yaml
Labels: approved, lgtm, size/L

#301 create 3.7 version branch for installer operators
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.release-3.7.yaml
  prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.release-1.3.yaml
  prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.release-1.1.yaml
  prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.release-1.4.yaml
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.release-1.5.yaml
Labels: approved, size/XL

#304 Create IBM.ibm-iam-operator.release-3.9.yaml
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.release-3.9.yaml
Labels: approved, lgtm, size/L

#306 enabled general release branches
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.release.yaml
Labels: approved, size/M

#307 enable prow build for ibm-crossplane-operator
  prow/cluster/jobs/IBM/ibm-crossplane-operator/IBM.ibm-crossplane-operator.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#308 enable eus stream for healthcheck operator
  prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.release-3.8.yaml
Labels: approved, lgtm, size/L

#305 enable 3.11 release for grafana-operator
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.release-1.11.yaml
Labels: approved, lgtm, size/L

#309 enable prow build for ibm-crossplane
  prow/cluster/jobs/IBM/ibm-crossplane/IBM.ibm-crossplane.master.yaml
  prow/config.yaml
Labels: approved, lgtm, size/L

#311 enable experimental
  prow/docker/build-tool/docker-entrypoint.sh
Labels: approved, size/S

#312 replace build image of crossplane
  prow/cluster/jobs/IBM/ibm-crossplane/IBM.ibm-crossplane.master.yaml
Labels: approved, size/S

#313 fix typo
  prow/docker/build-tool/docker-entrypoint.sh
Labels: approved, size/XS

#314 set mtu for DinD
  prow/docker/build-tool/docker-entrypoint.sh
Labels: approved, size/XS

#315 replace build image
  prow/cluster/jobs/IBM/ibm-crossplane/IBM.ibm-crossplane.master.yaml
Labels: approved, size/S

#316 add e2e test for odlm
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
Labels: approved, size/S

#317 update operator-sdk version to 1.3.0
  prow/docker/build-tool/Dockerfile
Labels: approved, size/S

#318 update odlm build image
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
Labels: approved, size/S

#319 update odlm build image
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
Labels: approved

#320 enable ssh for internal repo
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
Labels: approved, size/M

#322 enable release-1.4 for ingress-nginx
  prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.release-1.4.yaml
Labels: approved, lgtm, size/L

#321 enable release-3.8 for metering
  prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.release-3.8.yaml
Labels: approved, lgtm, size/L

#323 fix metering multiarch build
  prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.release-3.8.yaml
Labels: approved, lgtm, size/S
