Repository IBM/test-infra, pull requests merged in 2021-06, with the labels that each got.

#346 update prow job with new pipeline branches
  prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
Labels: approved, lgtm, size/XS

#347 Add branches for new pipelines
  prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.release-1.4.yaml
  prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.release-1.4.yaml
Labels: approved, lgtm, size/XL

#348 update branches for all jobs
  prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
Labels: approved, lgtm, size/S

#349 update install branches
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.master.yaml
  prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
Labels: approved, size/L

#350 Update IBM.ibm-iam-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.master.yaml
Labels: approved, size/S

#351 Update branches to prow build definition
  prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
Labels: approved, lgtm, needs-ok-to-test, size/M

#353 Updates to include fixes in the new pipelines
  prow/cluster/jobs/IBM/ibm-crossplane-operator/IBM.ibm-crossplane-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-crossplane/IBM.ibm-crossplane.master.yaml
Labels: approved, lgtm, size/M

#352 prow enablement for monitoring branches
  prow/cluster/jobs/IBM/ibm-monitoring-exporters-operator/IBM.ibm-monitoring-exporters-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-prometheus-operator-ext:/IBM.ibm-monitoring-prometheus-operator-ext.master.yaml
Labels: approved, lgtm, size/M

#354 Update IBM.ibm-iam-policy-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-iam-policy-operator/IBM.ibm-iam-policy-operator.master.yaml
Labels: approved, size/S

#355 added new branches for ibm-platform-api-operator builds
  prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.release-eus.yaml
Labels: approved, lgtm, size/S

#357 add release-future
  prow/cluster/jobs/IBM/ibm-crossplane-operator/IBM.ibm-crossplane-operator.master.yaml
Labels: approved, lgtm, size/XS

#356 added branches to cert manager builds
  prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.release-3.8.yaml
  prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
Labels: approved, lgtm, size/L

#358 add future branch for CS installer
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.master.yaml
  prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
Labels: approved, lgtm, size/L

#359 add release-future branch and delete release-cd branch
  prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
Labels: approved, lgtm, size/M

#360 add release-future branch for building
  prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
Labels: approved, lgtm, size/S

#362 monitoring - add release-future branch for building
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
Labels: approved, lgtm, size/S

#363 Licensing builds update
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.release.yaml
Labels: approved, lgtm, size/L
