Repository IBM/test-infra, pull requests merged in 2021-09, with the labels that each got.

#380 update config
  prow/config.yaml
Labels: approved, size/XS, ¯\_(ツ)_/¯

#385 enable project k for cs operator
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
Labels: size/XS

#386 add release-k branch for iam operator
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.master.yaml
Labels: approved, size/XS

#388 added release-k branch to cert-manager PROW build
  prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
Labels: approved, lgtm, size/XS

#389 Update IBM.ibm-commonui-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
Labels: approved, lgtm, size/XS
