Repository IBM/test-infra, pull requests merged in 2021-08, with the labels that each got.

#367 disable needs-rebase
  prow/plugins.yaml
Labels: approved, size/XS

#368 revert build images for crossplane operator
  prow/cluster/jobs/IBM/ibm-crossplane-operator/IBM.ibm-crossplane-operator.master.yaml
Labels: approved, size/S

#369 set preset sa in odlm e2e
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
Labels: approved, size/XS

#376 Add specific goal to build latest only on master
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
Labels: approved, lgtm, size/S

#377 update go verison 1.17
  prow/cluster/jobs/IBM/go-repo-template/ibm.go-repo-template-release-1.1.yaml
  prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.release-3.8.yaml
  prow/cluster/jobs/IBM/ibm-catalog-ui-operator/IBM.ibm-catalog-ui-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.release-3.6.yaml
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.release-3.7.yaml
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.release-4.0.yaml
  prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.master.yaml
  prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.release-1.2.yaml
  prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.release-1.3.yaml
  prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.release-1.4.yaml
  prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.release-1.5.yaml
  prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-elastic-stack-operator/IBM.ibm-elastic-stack-operator.release-v3.1.5.yaml
  prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.release-3.8.yaml
  prow/cluster/jobs/IBM/ibm-helm-api-operator/IBM.ibm-helm-api-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-helm-repo-operator/IBM.ibm-helm-repo-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.release-3.7.yaml
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.release-3.8.yaml
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.release-3.9.yaml
  prow/cluster/jobs/IBM/ibm-iam-policy-operator/IBM.ibm-iam-policy-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-licensing-hub-operator/IBM.ibm-licensing-hub-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.development.yaml
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-multicloudui-operator/IBM.ibm-metering-multicloudui-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.release-3.7.yaml
  prow/cluster/jobs/IBM/ibm-metering-operator/IBM.ibm-metering-operator.release-3.8.yaml
  prow/cluster/jobs/IBM/ibm-metering-receiver-operator/IBM.ibm-metering-receiver-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-metering-sender-operator/IBM.ibm-metering-sender-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-mongodb-operator/IBM.ibm-mongodb-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-mongodb-operator/IBM.ibm-mongodb-operator.release-1.2.yaml
  prow/cluster/jobs/IBM/ibm-mongodb-operator/IBM.ibm-mongodb-operator.release-1.3.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-exporters-operator/IBM.ibm-monitoring-exporters-operator.eus.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-exporters-operator/IBM.ibm-monitoring-exporters-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.release-1.11.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-prometheus-operator-ext:/IBM.ibm-monitoring-prometheus-operator-ext.eus.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-prometheus-operator-ext:/IBM.ibm-monitoring-prometheus-operator-ext.master.yaml
  prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.release-1.0.yaml
  prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.release-1.1.yaml
  prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.release-eus.yaml
  prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.release-1.3.yaml
  prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.release-1.4.yaml
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.release-1.4.yaml
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.release-1.5.yaml
  prow/cluster/jobs/IBM/test-infra/IBM.test-infra.master.yaml
Labels: approved, lgtm, size/XL
