Repository IBM/test-infra, pull requests merged in 2022-06, with the labels that each got.

#444 Improve build process / refactor existing jobs
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.development.yaml
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
Labels: approved, lgtm, size/L

#451 security audit release-ltsr pipeline enablement #53966
  prow/cluster/jobs/IBM/ibm-auditlogging-operator/IBM.ibm-auditlogging-operator.master.yaml
Labels: approved, lgtm, size/XS

#454 Adding ltsr branch for Monitoring
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
Labels: approved, lgtm, size/XS

#455 IBM Licensing Operator integration with LTSR Stream
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.development.yaml
  prow/cluster/jobs/IBM/ibm-licensing-operator/IBM.ibm-licensing-operator.master.yaml
Labels: approved, lgtm, size/S

#456 udpates for ui and ingress ltsr support
  prow/cluster/jobs/IBM/ibm-commonui-operator/IBM.ibm-commonui-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-ingress-nginx-operator/IBM.ibm-ingress-nginx-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-management-ingress-operator/IBM.ibm-management-ingress-operator.master.yaml
Labels: size/M, approved, lgtm

#457 Adding ltsr branch for installer squad
  prow/cluster/jobs/IBM/ibm-cert-manager-operator/IBM.ibm-cert-manager-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-namespace-scope-operator/IBM.ibm-namespace-scope-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-platform-api-operator/IBM.ibm-platform-api-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-secretshare-operator/IBM.ibm-secretshare-operator.master.yaml
  prow/cluster/jobs/IBM/operand-deployment-lifecycle-manager/IBM.operand-deployment-lifecycle-manager.master.yaml
Labels: size/M, approved, lgtm

#458 add release-ltsr branch to build jobs
  prow/cluster/jobs/IBM/ibm-common-service-operator/IBM.ibm-common-service-operator.master.yaml
Labels: approved, lgtm, size/XS

#459 added ltsr branch to common-service-webhook builds
  prow/cluster/jobs/IBM/ibm-common-service-webhook/IBM.ibm-common-service-webhook.master.yaml
Labels: approved, lgtm, size/S

#460 Add ltsr to Servicability prow build
  prow/cluster/jobs/IBM/ibm-healthcheck-operator/IBM.ibm-healthcheck-operator.master.yaml
Labels: approved, lgtm, size/S

#461 add release-ltsr branch to Crossplane pipelines
  prow/cluster/jobs/IBM/crossplane-provider-ibm-cloud/IBM.crossplane-provider-ibm-cloud.master.yaml
  prow/cluster/jobs/IBM/crossplane-provider-kubernetes/IBM.crossplane-provider-kubernetes.master.yaml
  prow/cluster/jobs/IBM/ibm-crossplane-operator/IBM.ibm-crossplane-operator.master.yaml
Labels: approved, lgtm, size/S
