Repository IBM/test-infra, pull requests merged in 2022-11, with the labels that each got.

#489 Update OWNERS
  prow/cluster/jobs/IBM/ibm-metering-operator/OWNERS
Labels: approved, lgtm, size/XS

#491 update zone and cluster in Makefile
  prow/Makefile
Labels: approved, lgtm, size/XS

#492 re trigger tool build after Makefile update
  prow/docker/build-tool/Dockerfile
Labels: approved, size/XS

#494 temporarily disable grafana prow jobs (ssh key config issue)
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.release-1.11.yaml
Labels: size/XL

#495 add prowjobs for the IAM operator future branch
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.master.yaml
Labels: size/XS

#496 do not error out docker login although multicloudlab credential unknown
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/XS

#497 add missing volume reference for ssh key
  prow/config.yaml
Labels: size/XS

#498 Revert "temporarily disable grafana prow jobs (ssh key config issue)"
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-monitoring-grafana-operator/IBM.ibm-monitoring-grafana-operator.release-1.11.yaml
Labels: size/XL
