Repository IBM/test-infra, pull requests merged in 2024-08, with the labels that each got.

#587 Update ibm-user-management-operator build branch
  prow/cluster/jobs/IBM/ibm-user-management-operator/IBM.ibm-user-management-operator.master.yaml
Labels: approved, lgtm, size/S, needs-ok-to-test

#588 Update build and check images to go 1.23
  prow/docker/build-tool/Dockerfile
  prow/docker/check-tool/Dockerfile
Labels: approved, size/XS

#590 Update golangci-lint to v1.60.1 to support go 1.23
  prow/docker/build-tool/Dockerfile
  prow/docker/check-tool/Dockerfile
Labels: approved, lgtm, size/XS
