Repository IBM/test-infra, pull requests merged in 2025-03, with the labels that each got.

#621 Update go from 1.23.6 to 1.23.7
  prow/docker/build-tool/Dockerfile
  prow/docker/check-tool/Dockerfile
Labels: approved, lgtm, size/XS

#623 Fix GOSUMDB value
  prow/docker/build-tool/Dockerfile
  prow/docker/check-tool/Dockerfile
Labels: approved, lgtm, size/XS, needs-ok-to-test

#624 Update iam build job with new build tool
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.master.yaml
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.release-3.7.yaml
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.release-3.8.yaml
  prow/cluster/jobs/IBM/ibm-iam-operator/IBM.ibm-iam-operator.release-3.9.yaml
Labels: size/M, approved
